INSERT INTO genre VALUES ('', 'Alternitive Rock', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Indie Rock', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Blues', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Classical', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Country', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Dance', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Electronic', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Hip Hop', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Rap', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Inspirational', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Asian Pop', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Jazz', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'New Age', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Latin', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Pop', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'R&B/Soul', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Reggae', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Hard Rock', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Classical Rock', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Vocal', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Folk', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Children\'s', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Comedy', 2, UTC_DATE(), 2, UTC_DATE() );
INSERT INTO genre VALUES ('', 'Holiday', 2, UTC_DATE(), 2, UTC_DATE() );
